# Generated by Django 2.2.5 on 2019-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_views',
            field=models.IntegerField(default=0),
        ),
    ]
